#version: '3.9'

services:
  nginx:
    image: nginx:alpine
    container_name: imzami_nginx
    restart: always
    ports:
      - "80:80"    # HTTP
      - "443:443"  # HTTPS
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /var/log/nginx:/var/log/nginx # Log directory
    depends_on:
      - php
    networks:
      - imzami_net

  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: imzami_php
    container_name: imzami_php
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
      - redis
    networks:
      - imzami_net

  db:
    image: mariadb:lts
    container_name: imzami_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mariadb/my.cnf:/etc/mysql/my.cnf # Custom MySQL configuration
      - /var/log/mysql:/var/log/mysql  # Log directory
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'mariadb-admin -u$DB_USER -p$DB_PASSWORD ping -h 127.0.0.1 || exit 1'"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - imzami_net
    #command: --bind-address=0.0.0.0  # Uncomment if you want to bind to all interfaces

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: imzami_pma
    restart: always
    ports:
      - "8080:80"  # Expose phpMyAdmin on port 8080
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_PORT: ${PMA_PORT}
    depends_on:
      - db
    networks:
      - imzami_net

  redis:
    image: redis:alpine
    container_name: imzami_redis
    restart: always
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
      - /var/log/redis:/var/log/redis # Log directory
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - imzami_net

volumes:
  db_data:
  redis_data:

networks:
  imzami_net:
    driver: bridge
